services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ~/.n8n:/home/node/.n8n
      - /Users/hauju/Projects/seggwat/n8n-nodes-seggwat:/home/node/.n8n/custom/n8n-nodes-seggwat
    extra_hosts:
      - 'host.docker.internal:host-gateway'
