services:
  n8n:
    image: n8nio/n8n:2.0.2
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ~/.n8n:/home/node/.n8n
    extra_hosts:
      - 'host.docker.internal:host-gateway'
